spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiosk
    username: user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      #      schema-locations: classpath:schema.sql
      schema-locations: classpath*:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
